import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import CoreProvider from "./_components/providers";

const roboto = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Magazord React test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <CoreProvider>{children}</CoreProvider>
      </body>
    </html>
  );
}
